apiVersion: v1
kind: Service
metadata:
  name: vigil-app
  namespace: vigil-app
  labels:
    app: vigil-app
spec:
  selector:
    app: vigil-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
